config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'user/show'
  get 'twitter/index'
  get 'home/show'

  resources :trucks do
    resources :locations, shallow: true
  end

  resources :locations

  root 'home#show'

end

app/models/truck.rb
class Truck < ActiveRecord::Base
  has_many :locations
  belongs_to :user
  validates :name, presence: true

  def most_recent_location
    locations.order(id: :desc).limit(1)
  end

  def tweets
    tweets = StreetTwitter.new.tweets_for_handle(twitter)[0..9]
    TweetLocationPersistor.new(tweets, id).persist_locations
    tweets
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize_user_by_truck, only: [:edit, :update, :destroy]

  # GET /trucks
  # GET /trucks.json
  def index
    @locations = Location.all
    @trucks = Truck.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trucks }
    end
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @truck }
    end
  end

  # GET /trucks/new
  def new
    @truck = Truck.new(user_id: current_user.id)
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render json: @truck, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(:name, :twitter, :email, :phone_1, :phone_2, :website, :user_id)
    end

    def authorize_user_by_truck
      redirect_to(truck_path(@truck), notice: "You have to be logged in to do that") unless @truck.user == current_user
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= form_for(@truck) do |f| %>
  <% if @truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% @truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div id="truck-field" class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter, class: "form-control" %>
  </div>
  <div id="truck-field" class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div id="truck-field" class="field">
    <%= f.label :phone_1 %><br>
    <%= f.text_field :phone_1, class: "form-control" %>
  </div>
  <div id="truck-field" class="field">
    <%= f.label :phone_2 %><br>
    <%= f.text_field :phone_2, class: "form-control" %>
  </div>
  <div id="truck-field" class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div id="truck-field" class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div id="truck-btn" class="actions">
    <%= f.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form' %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<h2>
  <strong>The Fleet is Rolling</strong>
  <div id="index_add_truck">
    <%= link_to fa_icon("truck", text: "Add a Truck"), new_truck_path, class: "btn btn-success" %>
  </div>
</h2>

<div class="panel panel-default">
  <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th><%= fa_icon("globe", text: "Last Location")%></th>
        <th><%= fa_icon("clock-o", text: "Last Active")%></th>
      </tr>
    </thead>

    <tbody>
      <% @trucks.order(id: :desc).each do |truck| %>
        <tr>
          <td><%= link_to "#{truck.name}", truck %></td>
          <td>
              <% if truck.locations.last %>
                <%= truck.locations.last.address %>
              <% end %>
          </td>
          <td><%= time_ago_in_words(truck.created_at) + " ago"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<div class="well">
<%= render 'form' %>
</div>

app/views/trucks/show.html.erb
<div class="col-md-7">
  <div id="info_pane" class="panel panel-default">
    <div id="truck_header" class="panel-heading">
      <h2>
        <%= image_tag(@truck.tweets.first.user.profile_image_url, class: "img-circle") %>
        <%= @truck.name %>
      </h2>
    </div>
    <div class="panel-body">
      <% if @truck.most_recent_location.first %>
      <div class="map-container-truck" id='mapTruck' style='width: 600px; height: 400px;'>
        <script type="text/javascript">
          var latlongTruckArray = [
            <% @truck.most_recent_location.each do |location|%>
            {
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [<%= location.longitude %>, <%= location.latitude %>]
              },
              "properties": {
                "title": " <%= location.truck.name %> ",
                "marker-symbol": "restaurant"

              }
            },
            <% end %>
          ];

          var centerCoordinates = [<%= @truck.most_recent_location.first.longitude %>, <%= @truck.most_recent_location.first.latitude %>]
        </script>
      </div>
      <div>
        <h4>Current Location</h4>
        <%= @truck.most_recent_location.first.address %>
      <% else %>
        <h4>Add a new location to display a map below.</h4>
        <% end %>
      </div>

      <div id="truck_button" class="btn group btn-group-justified" role="group">
        <%  if current_user %>
        <%= link_to fa_icon("globe", text: 'New Location'), new_truck_location_path(truck_id: @truck.id), class:"btn btn-success" %>
        <%= link_to fa_icon("pencil", text: "Edit"), edit_truck_path(@truck), class:"btn btn-primary" %>
        <% end %>
      </div>

      <div id="contact">
        <ul class="nav nav-list">
          <li>
            <p>
              <%= fa_icon("link") %>
              <%= link_to "#{@truck.name}'s website", @truck.website, target: "_blank" %></p>
          </li>
          <li>
            <p>
              <%= fa_icon("twitter") %>
              <%= link_to "#{@truck.twitter}", "http://twitter.com/#{@truck.twitter}", target: "_blank" %></p>
          </li>
          <% unless @truck.email == "" %>
          <li>
            <p>

              <%= fa_icon("envelope") %>
              <%= @truck.email %>
            </p>
          </li>
          <% end %>
          <% unless @truck.phone_1 == "" %>
          <li>
            <p>
              <%= fa_icon("phone") %>
              <%= @truck.phone_1 %>
            </p>
          </li>
          <% end %>
        </ul>
        <div class="btn group">
          <%  if current_user %>
          <%= link_to fa_icon("trash", text: 'Delete'), truck_path(@truck),
          method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="twitter_pane" class="col-md-5">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= fa_icon("twitter-square", text: "Recent Tweets")%></h3>
    </div>
    <div class="panel-body">
      <ul></li>
      <%  @truck.tweets.each do |tweet| %>
      <li><%= tweet.text %></li>
      <hr>
      <% end %>
    </ul>
  </div>
</div>
</div>