config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'user/show'
  get 'twitter/index'
  get 'home/show'

  resources :trucks do
    resources :locations, shallow: true
  end

  resources :locations

  root 'home#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trucks
  has_many :locations, through: :trucks

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

 def self.find_for_oauth(auth, signed_in_resource = nil)
   # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )

        user.save!
      end
    end

      # Associate the identity with the user if needed
   if identity.user != user
     identity.user = user
     identity.save!
   end
   user
 end

  def email_verified?
   self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/show.html.erb
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= fa_icon("user", text: "User")%></h3>
    </div>
    <div class="panel-body">
      <%= @user.email %>
      <div class="pull-right">
        <%= link_to fa_icon("pencil", text: "Edit"), edit_user_registration_path(@user), class:"btn btn-default" %>
      </div>
    </div>
  </div>

  <% @user.trucks.each do |truck| %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= fa_icon("truck", text: "Truck")%></h3>
    </div>
    <div class="panel-body">
        <div><%= truck.name %></div>
        <div>@<%= truck.twitter %></div>
      <div class="pull-right">
        <%= link_to fa_icon("eye", text: "Show"), truck_path(id: truck.id), class:"btn btn-success" %>
        <%= link_to fa_icon("twitter", text: "Twitter"), "http://twitter.com/#{truck.twitter}", target: "_blank", class:"btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= fa_icon("clock-o", text: "Last Updated")%></h3>
    </div>
    <div class="panel-body">
      <%= time_ago_in_words(truck.updated_at.inspect) %>
      <div class="pull-right">
        <%= link_to fa_icon("globe", text: "New Location"), new_truck_location_path(truck_id: truck.id), class:"btn btn-info" %>
      </div>
    </div>
  </div>
  <% end %>