config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'user/show'
  get 'twitter/index'
  get 'home/show'

  resources :trucks do
    resources :locations, shallow: true
  end

  resources :locations

  root 'home#show'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :truck
  belongs_to :user
  validates :longitude, presence: true
  validates :latitude, presence: true
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, if: :should_geocode?

  def should_geocode?
    return false if Rails.env.test?
    latitude? && longitude? || latitude_changed? && longitude_changed?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  # GET /locations
  # GET /locations.json
  def index
    most_recent = Location.select("max(id) as id").group(:truck_id)
    @locations = Location.where(id: most_recent).includes(:truck)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  def new
    @location = Location.new(truck_id: params["truck_id"])
    authorize_user_by_location
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    return if authorize_user_by_location
    respond_to do |format|
      if @location.save
        format.html { redirect_to truck_path(id: @location.truck_id), notice: 'Location was successfully created.' }
        format.json { render json: truck_path(id: @location.truck_id), status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:truck_id, :longitude, :latitude)
    end

    def authorize_user_by_location
      redirect_to(root_path, notice: "You have to be logged in to do that" ) if !@location.truck || @location.truck.user_id != current_user.id
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: 'form-control' %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: 'form-control' %>
  </div>
  </div>
  <div class="field">
    <%= f.hidden_field :truck_id %>
  </div>
  <div class="actions">
    <%= f.submit '..waiting..', class: 'btn btn-info btn-lg', disabled: true %>
  </div>
  <% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="map-container" id='mapIndex'>
  <script type="text/javascript">
    var latlongArray = [
      <% @locations.each do |location|%>
      {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [
              <%= location.longitude %>,
              <%= location.latitude %>
          ]
        },
        "properties": {
          truck_title: "<%= location.truck.name %>",
          address: "<%= location.address %>",
          url: "<%= truck_path(location.truck.id)%>"
        }
      },

      <% end %>
    ];

  </script>
</div>

app/views/locations/new.html.erb
<div class="container">
  <h3>New Location</h3>
  <div class="well">
    <%= render 'form' %>
  </div>
</div>

app/views/locations/show.html.erb
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>