config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'user/show'
  get 'twitter/index'
  get 'home/show'

  resources :trucks do
    resources :locations, shallow: true
  end

  resources :locations

  root 'home#show'

end

app/views/layouts/_footer.html.erb
  <div class="container">
    <div class="push"></div>
     <footer class="footer navbar-fixed-bottom">
       <aside id="copyright">
         &copy; StreetFleet 2016
       </aside>
       <aside id="social-icons">
         <%= link_to fa_icon("twitter 2x"),"https://twitter.com/streetfleetdc", target: 'blank'  %>
         <%= link_to fa_icon("facebook 2x"), "https://www.facebook.com/profile.php?id=100012221173835", target: 'blank'%>
         <%= link_to fa_icon("instagram 2x"), "https://www.instagram.com/streetfleetdc/", target: 'blank' %>
         <%= link_to fa_icon("github 2x"), "https://github.com/westmd23/street_fleet", target: 'blank' %>
       </aside>
     </footer>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StreetFleet" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon-cutlery.ico' %>
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script> <![endif]-->
    <%= javascript_include_tag 'https://api.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.js', 'data-turbolinks-track' => true, :type => "application/javascript" %>

  <link href='https://api.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.css' rel='stylesheet' />

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= fa_icon("cutlery", text: "StreetFleet") %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Map", locations_path  %></li>
            <li><%= link_to "Tweets", twitter_index_path %></li>
            <li><%= link_to "Trucks", trucks_path  %></li>
            <% if current_user %>
              <li><%= link_to "Profile", user_show_path(id: current_user.id) %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <%else%>
              <li><%= link_to "Login", new_user_session_path %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
      <%= render partial: "layouts/footer" %>


    <!-- /container -->

  </body>
</html>

app/views/layouts/locations.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StreetFleet" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon-cutlery.ico' %>
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script> <![endif]-->
    <%= javascript_include_tag 'https://api.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.js', 'data-turbolinks-track' => true, :type => "application/javascript" %>

  <link href='https://api.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.css' rel='stylesheet' />

  </head>
  <body>

    <div id="navbar" class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= fa_icon("cutlery", text: "StreetFleet") %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Map", locations_path  %></li>
            <li><%= link_to "Tweets", twitter_index_path %></li>
            <li><%= link_to "Trucks", trucks_path  %></li>
            <% if current_user %>
              <li><%= link_to "Profile", user_show_path(id: current_user.id) %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <%else%>
              <li><%= link_to "Login", new_user_session_path %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

      <%= bootstrap_flash %>
      <%= yield %>

      <%= render partial: "layouts/footer" %>

    <!-- /container -->

  </body>
</html>